"""
Reference Alembic migration that adds the Keycloak-related columns to `users`.

This file is NOT copied into migrations/versions/ as-is. Regenerate the
migration in the target project via `make migrate msg="add_keycloak_fields"`
after the User model has been extended, then compare the autogenerated file
against this reference and fix any missing pieces (named constraints,
`server_default`, index on `keycloak_id`).

revision identifiers are placeholders — Alembic fills them in when the
migration is regenerated locally.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic — replace on regeneration
revision: str = "<new_revision_hash>"
down_revision: Union[str, None] = "<previous_revision_hash>"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("first_name", sa.String(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("last_name", sa.String(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("keycloak_id", sa.String(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.add_column(
        "users",
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_index("ix_users_first_name", "users", ["first_name"])
    op.create_index("ix_users_last_name", "users", ["last_name"])
    op.create_index("ix_users_keycloak_id", "users", ["keycloak_id"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_users_keycloak_id", table_name="users")
    op.drop_index("ix_users_last_name", table_name="users")
    op.drop_index("ix_users_first_name", table_name="users")

    op.drop_column("users", "last_login")
    op.drop_column("users", "is_active")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "keycloak_id")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
